easy_admin:
    design:
        menu:
            - label: 'Bien-Etre'
              icon: 'newspaper-o'
              children:
                  - {entity: 'Services'}
                  - {entity: 'Provider'}
                  - {entity: 'Customer'}

    entities:
        Services:
            class: App\Entity\Services
            list:
              actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                fields:
                    - {property: 'name'}
                    - {property: 'description'}
        Provider:
            class: App\Entity\Provider
        Customer:
            class: App\Entity\Customer

